### PR TITLE
Upgrade build to JDK 21, default to Generational ZGC, add JDK 25 to CI

### PR DESCRIPTION
**Pull request by rustyrazorblade**
## Summary
- Bumps `sourceCompatibility`/`targetCompatibility`/Kotlin `jvmTarget` from 11 to 21; updates jib base image, deb/rpm runtime requirements, and all GitHub Actions workflows.
- Launch script and Docker image default to Generational ZGC (`-XX:+UseZGC -XX:+ZGenerational`), overridable via `JAVA_OPTS`/`JAVA_TOOL_OPTIONS`. JDK 23+ removed `-XX:+ZGenerational` (it's now ZGC's only mode), so the launch script detects the running JDK's major version and only passes the flag below 23.
- CI test matrix now covers JDK 21 and 25 (current + next LTS) instead of 17/21.
- Bumps `mockk` (1.12.7 → 1.14.3) and `junit-jupiter`/`junit-platform` (unified at 6.1.3, plus an explicit `junit-platform-launcher` dependency) — required, the old versions broke test discovery against JDK-21-targeted bytecode.
- Bumps `hadoop-common`/`hadoop-mapreduce-client-common` (3.4.1 → 3.4.3) to pick up [HADOOP-19212](https://issues.apache.org/jira/browse/HADOOP-19212), fixing `UserGroupInformation` throwing `UnsupportedOperationException` on JDK 24+ (Security Manager removal), which broke the Parquet output collector under JDK 25.
- Upgrades the Gradle wrapper 8.14.3 → 9.7.0 — required because Gradle's own daemon can't run on JDK 25 before 9.1.0 (this was the actual JDK 25 CI failure: `Unsupported class file major version 69`). Fixes the build script's deprecated Groovy constructs flagged for removal in Gradle 9/10, and bumps the jib plugin (3.3.0 → 3.5.4), which was calling a Gradle Convention API removed in Gradle 9.
- Pins detekt's task-level `jvmTarget` to 21 explicitly.

## Test plan
- [x] `./gradlew test ktlintCheck detekt distTar shadowJar` on JDK 21.0.10 — passes (2 pre-existing local-Docker-only failures unrelated to this change).
- [x] `./gradlew test40 test41 test50` on JDK 25.0.3 — passes (same 2 pre-existing failures).
- [x] `./gradlew jibDockerBuild` on both JDK 21 and 25 — image builds and runs; confirmed Generational ZGC active via `-Xlog:gc+init` and correct fallback to plain `-XX:+UseZGC` on JDK 25.
- [x] Extracted `distTar` output runs correctly; `LICENSE.txt` present at distribution root.
- [ ] CI matrix (this PR triggers it)

### CODE REVIEW

**Review by dcapwell — COMMENTED** [review]
from AI

BLOCKER — the conversion does not build
build.gradle.kts:203-204 nests tasks.named(String, Action) inside the tasks.register("testAllVersions") configuration action:
tasks.register("testAllVersions") {
    dependsOn(tasks.named("test40"), tasks.named("test41"), tasks.named("test50"))
    tasks.named("test41") { mustRunAfter(tasks.named("test40")) }   // illegal
    tasks.named("test50") { mustRunAfter(tasks.named("test41")) }   // illegal
Gradle forbids mutation of the task container while a task is being created:
> Could not create task ':testAllVersions'.
   > DefaultTaskContainer#named(String, Action) on task set cannot be executed in the current context.
This is a hard failure, not a warning. It breaks ./gradlew testAllVersions and ./gradlew tasks — both documented commands (CLAUDE.md, README.md). The Groovy original ran these statements at script top level, so they always applied eagerly. The two statements must move out of the register block to top level. I confirmed the build succeeds once they are moved.
This also means the PR test plan (./gradlew test40 test41 test50, test ktlintCheck detekt distTar shadowJar) never exercised testAllVersions.

File: build.gradle.kts [hunk 1]
```diff
@@ -0,0 +1,336 @@
...
+    }
+    from {
+        image = "eclipse-temurin:21-jre"
+    }
+    container {
+        // Generational ZGC by default; override at "docker run" time with
+        // -e JAVA_TOOL_OPTIONS="..." to select a different collector.
+        environment =
+            mapOf(
+                "JAVA_TOOL_OPTIONS" to "-XX:+UseZGC -XX:+ZGenerational",
```
Comment (dcapwell) [inline build.gradle.kts]: `bin/cassandra-easy-stress` explicitly avoids `-XX:+ZGenerational` once we are jdk 23+

File: build.gradle.kts [hunk 2]
```diff
@@ -0,0 +1,336 @@
...
+    implementation(libs.dropwizard.metrics.core)
+    implementation(libs.prometheus.simpleclient)
+    implementation(libs.prometheus.simpleclient.dropwizard)
+    implementation(libs.prometheus.simpleclient.httpserver)
+
+    implementation(libs.guava)
+    implementation(libs.mordant)
+    implementation(libs.progressbar)
+    implementation(libs.hdrhistogram)
+    implementation(libs.agrona) // can't use the 2.x or 1.23+ line as it requires JDK 17
```
Comment (dcapwell) [inline build.gradle.kts]: this comment doesn't look accurate anymore

**Comment by rustyrazorblade** [comment]
Thanks for the review — pushed fixes for all four points in 0ae27d0:

1. **Blocker (`testAllVersions`/`./gradlew tasks` failure)**: confirmed and fixed. Moved the `mustRunAfter` wiring out of the `register("testAllVersions") { }` block to top level — Gradle forbids mutating the task container from inside another task's configuration action. `./gradlew tasks` and `./gradlew testAllVersions` both verified working again.
2. **jib GC-flag drift**: the container's `JAVA_TOOL_OPTIONS` now derives from the same JDK-version check as `bin/cassandra-easy-stress`, instead of hardcoding `-XX:+ZGenerational`. No behavior change today (base image pinned to JDK 21), but keeps the two launch paths from silently diverging if the base image is ever bumped to JDK 23+.
3. **Stale `agrona` comment**: fixed — the JDK 17 constraint it referenced no longer applies now that the project targets JDK 21.
4. **JDK 25 compile safety**: added `-Xjdk-release=21` to the Kotlin compile tasks. `jvmTarget` alone only stamps the output class file version — it doesn't restrict the compiler to APIs that actually exist on JDK 21. Without this, code compiled under JDK 25 could reference a JDK 22-25-only stdlib API, compile cleanly, and only fail with `NoSuchMethodError` on a real JDK 21 at runtime. No current behavior change; verified clean builds on both JDK 21.0.10 and JDK 25.0.3.

Re-verified locally on both JDK 21 and JDK 25: `test`, `ktlintCheck`, `detekt`, `distTar`, `shadowJar`, `jibDockerBuild` all pass (only the 2 pre-existing local-Docker-only test failures, unrelated).

**Comment by rustyrazorblade** [comment]
Pushed one more change (6690b64), reversing the \`-Xjdk-release=21\` approach from the previous commit in favor of a simpler design: the build now targets whatever JDK is actually compiling it (JavaVersion.current()), instead of always forcing JDK 21 bytecode regardless of the build JDK.

Rationale: the release-artifact-building CI jobs (\`build\`, \`build-check\`, \`create-test-artifact\`) are already hardcoded to JDK 21 — that's the actual single source of truth for what the shipped artifact requires. Pinning the build script to a fixed "21" independently of that was just a second place that could drift out of sync, the same class of issue already fixed for the jib GC flags.

This required two follow-on bumps to actually work:
- \`kotlin\` 2.2.20 → 2.4.10 — JDK 25 as an explicit Kotlin compiler target requires Kotlin 2.3.0+; 2.2.20 caps out at JVM_24 and fails outright when asked to target 25.
- \`kover\` 0.9.2 → 0.9.9 — 0.9.2 calls an internal Kotlin Gradle plugin API removed in the Kotlin 2.4 line, which broke \`koverXmlReport\`'s configuration entirely once Kotlin was bumped.

Verified via \`javap\`: building under JDK 21 now produces class file major version 65 (JDK 21), building under JDK 25 produces major version 69 (JDK 25) — confirmed on both. Full suite (test/ktlintCheck/detekt/distTar/shadowJar/jibDockerBuild/tasks/testAllVersions) re-verified on both JDKs.

**Review by dcapwell — APPROVED** [review]
